// Generated by TMBtools: do not edit by hand

#define TMB_LIB_INIT R_init_bifrost_TMBExports
#include <TMB.hpp>
#include "NormalNLL.hpp"

template<class Type>
Type objective_function<Type>::operator() () {
  DATA_STRING(model);
  if(model == "NormalNLL") {
    return NormalNLL(this);
  } else {
    error("Unknown model.");
  }
  return 0;
}
